spring:
  jpa:
    properties:
      hibernate:
        #show_sql: true # System.out 방식 로그
        format_sql: true #쿼리 가독성 좋게(한줄X)
        highlight_sql: true #SQL 키워드 강조
        use_sql_comments: true #주석으로 SQL 설명 추가해준다

logging:
  level:
    org:
      hibernate:
        SQL: debug # logger 방식 로그
        orm:
          jdbc:
            bind: trace #SQL 로그에 ?값을 보여준다

      springframework.security: DEBUG
      org.springframework.web: DEBUG

