spring:
  config:
    import: optional:file:.env[.properties] #.env파일 가져오기
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEVELOP_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create